version: '3.7'

services:
  www:
    tty: true
    image: node:latest
    command: sh -c "cd /app && npm run start"
    working_dir: /app
    volumes:
      - '.:/app'
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    labels:
      girouette.domains: test.julienphilippon.devel:3000
      girouette.group: Test
